<script lang="ts" context="module">
  export const _FREE_ = 0;
  
  export enum W {
    EGLE = 1,
    RBRK,
    PSTN,
    GSTN,
    BSTN,
    MOSS,
    WOOD,
    CSTN,
  }
  
  export enum S {
    LITE = -3,
    PLLR,
    BRRL,
  }
  
  export const WORLD_MAP = [
    [W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.GSTN, W.GSTN, W.MOSS, W.GSTN, W.GSTN, W.MOSS, W.GSTN, W.MOSS, W.GSTN, W.GSTN, W.GSTN, W.MOSS, W.GSTN],
    [W.CSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.CSTN, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.GSTN],
    [W.CSTN, _FREE_, W.PSTN, W.PSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.CSTN, W.CSTN, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.MOSS],
    [W.CSTN, _FREE_, S.BRRL, W.PSTN, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, W.MOSS],
    [W.CSTN, _FREE_, W.PSTN, W.PSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.CSTN, W.CSTN, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.GSTN],
    [W.CSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.CSTN, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.MOSS, W.MOSS, W.MOSS, _FREE_, W.MOSS, W.GSTN, W.MOSS],
    [W.CSTN, W.CSTN, W.CSTN, W.CSTN, _FREE_, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.CSTN, W.GSTN, W.GSTN, W.GSTN, W.GSTN, W.GSTN, W.GSTN, W.MOSS, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.MOSS],
    [W.WOOD, W.WOOD, W.WOOD, W.WOOD, _FREE_, W.WOOD, W.WOOD, W.WOOD, W.WOOD, _FREE_, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, W.GSTN, _FREE_, W.GSTN, _FREE_, W.MOSS, _FREE_, W.MOSS],
    [W.WOOD, W.WOOD, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.WOOD, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, W.CSTN, W.MOSS, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.MOSS],
    [W.WOOD, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, S.BRRL, W.CSTN, W.MOSS, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.GSTN],
    [W.WOOD, _FREE_, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, _FREE_, _FREE_, S.BRRL, W.CSTN, W.MOSS, _FREE_, W.MOSS, _FREE_, W.MOSS, _FREE_, W.MOSS],
    [W.WOOD, W.WOOD, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.WOOD, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, _FREE_, W.CSTN, W.CSTN, W.MOSS, W.GSTN, W.MOSS, _FREE_, W.MOSS, W.MOSS, W.MOSS],
    [W.WOOD, W.WOOD, W.WOOD, W.WOOD, _FREE_, W.WOOD, W.WOOD, W.WOOD, W.WOOD, W.CSTN, W.CSTN, W.GSTN, _FREE_, W.MOSS, W.CSTN, W.GSTN, W.CSTN, W.PSTN, W.PSTN, W.PSTN, _FREE_, W.PSTN, W.PSTN, W.PSTN],
    [W.RBRK, W.RBRK, W.RBRK, W.RBRK, _FREE_, W.RBRK, W.RBRK, W.RBRK, W.RBRK, W.GSTN, W.MOSS, W.GSTN, _FREE_, _FREE_, W.MOSS, _FREE_, W.MOSS, W.PSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.PSTN],
    [W.RBRK, W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.RBRK, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.GSTN, W.PSTN, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, W.PSTN],
    [W.RBRK, S.BRRL, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.GSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.GSTN, W.PSTN, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.PSTN],
    [W.EGLE, S.BRRL, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.EGLE, W.GSTN, W.GSTN, W.GSTN, W.GSTN, W.GSTN, W.MOSS, _FREE_, W.MOSS, W.PSTN, W.PSTN, _FREE_, _FREE_, _FREE_, W.PSTN, W.PSTN],
    [W.RBRK, S.BRRL, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.RBRK, W.RBRK, W.EGLE, W.RBRK, W.RBRK, W.RBRK, W.MOSS, W.MOSS, _FREE_, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN],
    [W.RBRK, W.RBRK, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, W.RBRK, W.RBRK, W.RBRK, S.PLLR, S.PLLR, S.PLLR, W.RBRK, W.RBRK, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, _FREE_, _FREE_, W.BSTN, W.BSTN],
    [W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN],
    [W.EGLE, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, S.LITE, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.BSTN],
    [W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, W.BSTN],
    [W.RBRK, W.RBRK, _FREE_, _FREE_, _FREE_, _FREE_, _FREE_, W.RBRK, W.RBRK, W.RBRK, _FREE_, _FREE_, _FREE_, W.RBRK, W.RBRK, _FREE_, W.BSTN, _FREE_, W.BSTN, _FREE_, _FREE_, _FREE_, W.BSTN, W.BSTN],
    [W.RBRK, W.RBRK, W.RBRK, W.RBRK, W.EGLE, W.RBRK, W.RBRK, W.RBRK, W.RBRK, W.RBRK, W.RBRK, W.EGLE, W.RBRK, W.RBRK, W.RBRK, W.BSTN, W.BSTN, W.BSTN, W.BSTN, W.BSTN, W.BSTN, W.BSTN, W.BSTN, W.BSTN],
  ];

  export function getCell(x: number, y: number) {
    return WORLD_MAP[Math.floor(y)][Math.floor(x)];
  }
</script>
